---
title: "Hmwk3 Rmarkdown"
author: "Matthew Murray"
output: pdf_document
---

Homework 3 for Tools4RR
	Perform exhaustive permutation test with t-statistic

```{r define functions, echo=FALSE}
#
binary.v <-
    function(n)
{
    x <- 1:(2^n)
    mx <- max(x)
    digits <- floor(log2(mx))
    ans <- 0:(digits-1); lx <- length(x)
    x <- matrix(rep(x,rep(digits, lx)),ncol=lx)
    (x %/% 2^ans) %% 2
}
# permutation test
perm.test <-
    function(x, y, var.equal=TRUE)
{
    # number of data points
    kx <- length(x)
    ky <- length(y)
    n <- kx + ky

    # Data re-compiled
    X <- c(x,y)
    z <- rep(1:0,c(kx,ky))

    tobs <- t.test(x,y,var.equal=var.equal)$statistic

    o <- binary.v(n)  # indicator of all possible samples
    o <- o[,apply(o,2,sum)==kx]
    nc <- choose(n,kx)
    allt <- 1:nc
    for(i in 1:nc) {
        xn <- X[o[,i]==1]
        yn <- X[o[,i]==0]
        allt[i] <- t.test(xn,yn,var.equal=var.equal)$statistic
    }

    attr(allt, "tobs") <- tobs

    allt
}
```

Here is some test data.

```{r test data}
x <- c(6.20, 5.72, 6.07, 6.75, 5.50, 6.39, 4.30, 4.96, 5.48)
y <- c(6.49, 6.52, 6.28, 8.59, 7.18, 4.92, 6.74, 7.27)
```



Here we run the permutation test
```{r}
permt <- perm.test(x, y)
```

Extract the observed t-statistic (saved as attribute)
```{r}
tobs <- attr(permt, "tobs")
```

Calculate the p-value based on the observed test statistic 
```{r}
pval <- mean(abs(permt) >= abs(tobs))
```

Save and plot results 
```{r, echo=FALSE}
save(permt, tobs, pval, file="permt_results.RData")
```
```{r, results='hide'}
pdf("hw2_plot.pdf", height=7.5, width=10, pointsize=14)
hist(permt, breaks=200, xlab="t-statistic", las=1,
     main = paste("P-value =", round(pval, 3)))
abline(v=tobs, lwd=2, col="violetred")
dev.off()
```









